---
- name: Docker login 
  command: docker login --username {{ usernamed }} --password {{ passwordd }} docker.io

- debug:
    msg: "Port is: {{ app_port }}"

- name: Docker image build 
  command: docker build -t {{ registry_docker }}:{{ build_number }} --build-arg APPD_PORT={{ app_port }} {{ workspacej }}

- name: Docker image push
  command: docker push {{ registry_docker }}:{{ build_number }}

- name: Docker local image delete
  command: docker rmi {{ registry_docker }}:{{ build_number }}

