---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: yuriy
  labels:
    app: redis
    type: server
spec:
  # type: ClusterIP
  selector:
    app: redis
    type: server
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: yuriy
spec:
  selector:
    matchLabels:
      app: redis
      type: server
  serviceName: "redis-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        type: server
    spec:
      containers:
      - name: redis-server
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data-pvc
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: hcloud-volumes
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
  # name: redis-pvc
  # namespace: yuriy
# spec:
  # accessModes:
    # - ReadWriteOnce
  # resources:
    # requests:
      # storage: 5Gi
  # storageClassName: hcloud-volumes
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: redis-deployment
  # namespace: yuriy
# spec:
  # selector:
    # matchLabels:
      # app: redis
      # type: server
  # replicas: 1
  # template:
    # metadata:
      # labels:
        # app: redis
        # type: server
    # spec:
      # containers:
      # - name: redis-server
        # image: redis
        # resources:
          # requests:
            # cpu: 200m
            # memory: 200Mi
        # ports:
        # - containerPort: 6379
        # volumeMounts:
        # - name: redis-data
          # mountPath: /data
      # volumes: 
      # - name: redis-data
        # persistentVolumeClaim:
          # claimName: redis-pvc
# ---
# apiVersion: apps/v1
# kind: PersistentVolumeClaim
# metadata:
  # name: redis-pvc
  # namespace: yuriy
# spec:
  # accessModes:
    # - ReadWriteOnce
  # resources:
    # requests:
      # storage: 5Gi
  # storageClassName: hcloud-volumes